### ISSUE TITLE
Update "Elixir Jump to Test" extension into "Elixir Test"

### ISSUE THREAD

**Issue by samuelpordeus** [samuelpordeus/elixir-test#13]
Let's pivot our extension and do some epic changes 💥!

We are planning to add a few more features related to test to this extension:
* Run test that the cursor is currently on
* Run all tests on the currently opened file
* Run the whole test suite

For that reason, we need to change its name to something more generic, and the chosen name was `Elixir Test`!

**Comment by CaiqueMitsuoka** [comment]
![oooh my goood](https://media.giphy.com/media/5VKbvrjxpVJCM/giphy.gif)

**Comment by GuSilverFlame** [comment]
rad
